name: K6 Performance Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  test:
    environment: Dev
    env:
      API_URL: ${{ secrets.API_URL }}
      CLIENT_ID: ${{ secrets.CLIENT_ID }}
      CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
      SCOPE: ${{ secrets.SCOPE }}    
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'  # o la versión que necesites

    - name: Install K6
      run: |
        sudo gpg -k
        sudo gpg --no-default-keyring --keyring /usr/share/keyrings/k6-archive-keyring.gpg --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys C5AD17C747E3415A3642D57D77C6C491D6AC1D69
        echo "deb [signed-by=/usr/share/keyrings/k6-archive-keyring.gpg] https://dl.k6.io/deb stable main" | sudo tee /etc/apt/sources.list.d/k6.list
        sudo apt-get update
        sudo apt-get install k6

    - name: Verify K6 Installation
      run: |
        k6 version  # Verifica que k6 se haya instalado correctamente

    - name: Load Environment Variables
      run: |
        echo "API_URL=${{ secrets.API_URL }}" >> $GITHUB_ENV
        echo "CLIENT_ID=${{ secrets.CLIENT_ID }}" >> $GITHUB_ENV
        echo "CLIENT_SECRET=${{ secrets.CLIENT_SECRET }}" >> $GITHUB_ENV
        echo "SCOPE=${{ secrets.SCOPE }}" >> $GITHUB_ENV    

    - name: Run K6 Tests
      id: run-tests
      run: |
        k6 run --out json=results.json k6_script.js
    - name: Upload k6 test results  #to upload files as artifacts to pipeline
      uses: actions/upload-artifact@v2
      with:
        name: k6-test-results
        path: results.json